### ISSUE TITLE
Path to SOAgentSetup.exe is incorrect.

### ISSUE THREAD

**Issue by Jassen-Kinetics** [N-able/InstallAgent#2]
Very new to VBScripting and trying to deploy this.

When testing I am getting the following key written in to the registry and the script won't run as the path is incorrect.

![image](https://cloud.githubusercontent.com/assets/25357488/22316364/8cf7291e-e3d1-11e6-9913-b4db76c8f19d.png)

Does anyone know where this is coming from?

Thanks
Jassen

**Comment by joncz** [comment]
Did you set up the _InstallAgent.ini_ file?
