### ISSUE TITLE
Version 11 no longer supports XP/2003

### ISSUE THREAD

**Issue by jarrodmast** [N-able/InstallAgent#3]
The scripted installer is now removing agents on XP/03 when attempting to install upgrades leaving devices with no agent installed.
The easy workaround is to exclude the XP/03 device however we should probably have a way to direct legacy agent installers to a separate config or bail quietly without breaking the current agent.

**Comment by joncz** [comment]
Create a file called nable_disable.mrk in %WinDir% and the installer will quit immediately.
