### ISSUE TITLE
The InstallAgent.vbs could not be reached on the network.

### ISSUE THREAD

**Issue by XDuffmanX** [N-able/InstallAgent#5]
Can someone help me with this. Its located on the \\domain\netlogon\agent folder. I can browse to it but in eventvwr it gives me the top error.

Also when I try to run it with cscript i get the following error
Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved.

Please wait whilst the  agent is checked.

\\Domain\NETLOGON\AGENT\INSTALLAGENT.VBS(500, 3) Microsoft VBScript runtime err
or: Type mismatch: 'CDbl'

The server is a 2012 R2.

Thanks in advance

**Comment by XDuffmanX** [comment]
![capture](https://user-images.githubusercontent.com/43400732/45736498-691cbd80-bbeb-11e8-9663-894e0612507e.PNG)

**Comment by whader** [comment]
> Can someone help me with this. Its located on the \domain\netlogon\agent folder. I can browse to it but in eventvwr it gives me the top error.
> 
> Also when I try to run it with cscript i get the following error
> Microsoft (R) Windows Script Host Version 5.8
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Please wait whilst the agent is checked.
> 
> \Domain\NETLOGON\AGENT\INSTALLAGENT.VBS(500, 3) Microsoft VBScript runtime err
> or: Type mismatch: 'CDbl'
> 
> The server is a 2012 R2.
> 
> Thanks in advance

I received the same "could not be reached error" and realized I was only passing the DOMAIN name in the parameters and not including the .local. Adding .local to the startup script parameters successfully launches the VBS script.

**Comment by whader** [comment]
Despite being able to successfully call the VBS file in my GPO, it seems the MSI file does not receive the correct command line switches. When I run this using the command ` cscript \\domain.local\netlogon\agent\installagent.vbs /site:XXX ` the MSI Help file pops up. 

The command logged into Application Log is ` \\domain.local\Netlogon\Agent\SOAgentSetup.exe /S /v"/qn CUSTOMERID=XXX CUSTOMERSPECIFIC=1 SERVERPROTOCOL=HTTPS SERVERADDRESS=n-centralserver.domain.com SERVERPORT=443`

Any help would be greatly appreciated!

**Comment by jamesweakley** [comment]
Hi all, not sure if the original author (@timwiser) or @joncz are still monitoring this repo. I can't really help as I no longer work for an MSP. If anyone manages to fix the issue, I'm happy to grant access to the repo to update the script.

**Comment by whader** [comment]
Thank you @jamesweakley but we figured it out! 

I was attempting to use a site specific AgentSetup.exe instead of the generic one found [here](https://ncentral.fbhl.com/download/12.0.0.365/winnt/N-central/installNableAgent.bat)
