### ISSUE TITLE
Windows 10 CDBL issue.

### ISSUE THREAD

**Issue by XDuffmanX** [N-able/InstallAgent#6]
Hi.

I get the above issue and i do not know how to fix it. Windows 7 works. Windows 10 gives an issue. It looks like its got something to do with checking the OS.

![image](https://user-images.githubusercontent.com/43400732/48259804-e0b7dd80-e421-11e8-87cd-40615c281e0c.png)

Any help will be appreciated.

**Comment by joncz** [comment]
Only reason I can think this would occur is if the Win 10 systems are localized to use ',' as the decimal separator.  In this case, you'd need to change line 501 to use a comma instead of decimal point.

ref: [https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000PANpSAO](url)
