### ISSUE TITLE
Windows Imaging Component URLs are Dead

### ISSUE THREAD

**Issue by djvenja** [N-able/InstallAgent#8]
It seems that the URLs for the Windows Imaging Component files (**wic_x86_enu.exe** and **wic_x64_enu.exe**) are dead. Can't seem to find a new Microsoft source for these files. Please can these files be uploaded the the GitHub repo?
[wic_files.zip](https://github.com/N-able/InstallAgent/files/5123655/wic_files.zip)

**Comment by prejay** [comment]
Files have been uploaded.
